#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 104
#define YY_END_OF_BUFFER 105
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[296] =
    {   0,
        0,    0,    0,    0,  105,  101,  100,  104,  101,    1,
       91,  101,   83,   84,   89,   87,   82,   88,   75,  101,
       93,   93,   93,   92,   80,   76,   77,   95,   16,   95,
       95,   60,   95,   95,   95,   95,   14,   61,   15,   95,
       52,   43,   95,   95,   95,   95,   78,   79,   81,   85,
       86,  102,  103,    0,   94,    0,    0,    0,    0,   93,
       90,    0,    0,    4,    0,    0,    2,   18,    5,    0,
       98,   98,    0,    0,   93,   95,   95,   95,   95,   95,
       95,   95,    8,   95,   95,   95,   95,   95,   53,   95,
       95,   95,   95,   95,   95,    9,   95,   95,   95,   25,

       95,   95,   95,   73,   95,   95,   95,   55,   95,   95,
       95,   95,   95,   72,   95,   95,   95,   95,   10,   95,
       96,    0,    0,   27,    0,    0,    0,    0,    0,    0,
       98,   98,   98,   98,   98,    0,   99,   99,   30,   31,
       95,   95,   95,   46,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   39,   95,
       95,   95,   64,   95,   95,   95,   95,   95,   95,   38,
       48,   50,   62,   95,   95,   95,   95,   95,   42,   95,
       37,   95,   22,    0,    0,    0,    0,    0,   97,   97,
        0,   99,   99,   99,   99,   99,   95,   95,   95,   95,

       95,   95,   95,   45,   54,   65,   49,   74,   28,   95,
       47,   56,   95,   29,   95,   95,   95,   95,   95,   95,
       26,   95,   95,   95,   95,   95,   95,   95,   63,   71,
       95,   95,    0,   21,    6,   19,    0,   97,   97,   97,
       97,   97,   95,   68,   95,   95,   58,   41,   57,   17,
       95,   66,   95,   32,   95,   51,   95,   95,   34,   36,
       23,   59,   95,   35,   40,   95,   95,    0,   95,   95,
       95,   95,   95,   33,    3,   44,    7,   95,   95,   20,
       11,   95,   95,   95,   95,   24,   95,   70,   69,   12,
       95,   13,   95,   67,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    8,    1,    1,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   19,
       20,   18,   18,   18,   18,   18,   18,   21,   22,   23,
        1,   24,    1,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   41,
       50,   51,   52,   53,   54,    1,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   64,   65,   66,   67,   68,
       69,   70,   41,   71,   72,   73,   74,   75,   76,   77,
       78,   41,   79,    1,   80,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   41,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   41,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   41,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[81] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    3,    4,    2,    2,    2,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        5,    1,    1,    6,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1
    } ;

static const flex_int16_t yy_base[310] =
    {   0,
        0,    0,  107,  104,   96, 2528, 2528, 2528,   78, 2528,
     2528,   67, 2528, 2528, 2528, 2528, 2528,  101, 2528,   73,
       79,   93,  147, 2528, 2528, 2528, 2528,   86,  193,  246,
      165,  177,  302,  184,  230,  257,  274,  294,  362,  287,
      374,  366,  353,  404,  423,  429, 2528, 2528, 2528, 2528,
     2528, 2528, 2528,   97, 2528,   96,  118,  334,  437,  454,
     2528,   94,   95,   85,  105,  109, 2528,   94, 2528,  130,
      484,  494,  168,  221,  500,  506,  512,  521,  527,  537,
      543,  534,  540,  549,  604,  610,  600,  573,  609,  617,
      619,  655,  661,  663,  669,  683,  707,  716,  722,  738,

      758,  760,  777,  780,  793,  812,  813,  828,  845,  864,
      872,  863,  903,  900,  919,  920,  936,  952,  939,  967,
     2528,  148,  154, 2528,  154,  145,  174,  197,  395,  445,
      999, 1014, 1025, 1031, 1039,  214,  656, 1007, 1047, 1054,
     1044, 1053, 1104, 1066, 1098, 1104, 1114, 1140, 1149, 1164,
     1180, 1188, 1196, 1113, 1204, 1223, 1224, 1239, 1240, 1259,
     1272, 1285, 1291, 1299, 1318, 1327, 1335, 1344, 1354, 1363,
     1371, 1380, 1390, 1407, 1422, 1406, 1446, 1466, 1438, 1474,
     1460, 1488, 2528,  198,  208,  219,  240,  305, 1135, 1521,
      320, 1532, 1539, 1546, 1552, 1558, 1549, 1559, 1610, 1617,

     1573, 1611, 1609, 1619, 1625, 1635, 1651, 1657, 1667, 1673,
     1683, 1689, 1699, 1709, 1725, 1715, 1731, 1751, 1767, 1775,
     1783, 1784, 1815, 1828, 1831, 1830, 1866, 1874, 1850, 1876,
     1909, 1912,  285, 2528, 2528, 2528,  326, 1905, 1911, 1942,
     1948, 1956, 1955, 1956, 1993, 2015, 1976, 1998, 2007, 2015,
     2034, 2042, 2061, 2058, 2074, 2077, 2093, 2094, 2096, 2113,
     2129, 2132, 2145, 2146, 2148, 2165, 2181,  245, 2184, 2216,
     2243, 2217, 2238, 2241, 2244, 2257, 2260, 2276, 2284, 2528,
     2292, 2323, 2347, 2330, 2347, 2344, 2380, 1985, 2377, 2382,
     2383, 2396, 2397, 2399, 2528, 2471, 2477, 2482,   88, 2486,

     2491, 2496, 2501,   87,   81, 2506, 2511, 2516, 2521
    } ;

static const flex_int16_t yy_def[310] =
    {   0,
      295,    1,  296,  296,  295,  295,  295,  295,  297,  295,
      295,  298,  295,  295,  295,  295,  295,  295,  295,  299,
      300,  300,  300,  295,  295,  295,  295,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,   29,  301,  301,  301,  301,  295,  295,  295,  295,
      295,  295,  295,  297,  295,  295,  295,  298,  298,  300,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      302,  303,  295,  304,  300,  300,  300,  300,  300,  300,
      301,   45,   45,   45,  301,  301,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,  106,   45,   45,   45,   45,   45,   45,   45,   45,
      295,  295,  295,  295,  295,  295,  295,  295,  305,  299,
      302,  302,  302,  302,  303,  295,  306,  307,  300,  300,
       45,   45,  300,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,  295,  295,  295,  295,  295,  295,  308,  309,
      295,  306,  306,  306,  306,  307,   45,   45,  300,  300,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,  295,  295,  295,  295,  295,  308,  308,  308,
      308,  309,   45,   45,  300,  300,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,  295,   45,  300,
      300,   45,   45,   45,   45,   45,   45,   45,   45,  295,
       45,  300,  300,   45,   45,   45,   45,  300,  300,   45,
       45,   45,   45,   45,    0,  295,  295,  295,  295,  295,

      295,  295,  295,  295,  295,  295,  295,  295,  295
    } ;

static const flex_int16_t yy_nxt[2609] =
    {   0,
        6,    7,    8,    7,    7,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   28,   35,   36,   37,   38,   39,   40,   28,   41,
       28,   42,   43,   44,   45,   28,   46,   28,   28,   47,
        6,   48,   49,    6,   28,   29,   30,   31,   32,   33,
       34,   28,   35,   36,   37,   38,   39,   40,   28,   41,
       42,   43,   44,   45,   28,   46,   28,   28,   50,   51,
       55,   56,  190,   55,   57,   57,   57,   70,  138,   72,
       71,   71,   71,   73,   74,  295,   75,   75,   75,   55,

       73,   74,   55,   80,   80,   80,   53,   73,   74,   53,
       75,   75,   75,   57,   57,   57,  295,   59,   60,   60,
       60,  122,   78,  123,   61,   62,  121,  124,   63,  125,
       64,  295,   77,  126,  295,   57,   57,   57,   65,   77,
       66,  295,  127,   67,   68,   69,   77,   71,   71,   71,
      295,  122,   78,  123,  295,   62,  124,  295,   63,  125,
       64,   73,   74,  126,   75,   75,   75,  295,   65,  295,
       66,  127,   67,   68,   69,  183,   79,  295,  295,   73,
       74,  295,   80,   80,   80,   80,   80,   80,  186,  184,
      185,   73,   74,   90,   80,   80,   80,   91,   73,   74,

       77,   80,   80,   80,   92,  183,   79,   73,   74,  295,
       80,   80,   80,  187,  134,  134,  134,  186,   77,  184,
      185,   82,   83,   90,   93,   99,  233,   91,   84,   85,
       77,  137,  137,  137,   92,  136,  234,   77,  137,  137,
      137,  295,  295,  187,   73,   74,   77,   80,   80,   80,
      235,   82,   83,   93,   99,  295,  233,  100,   84,   85,
       73,   74,  295,   80,   80,   80,  234,  101,  236,  295,
       86,   73,   74,  280,   80,   80,   80,   87,  295,  295,
      235,  295,  295,   77,   88,   89,  295,  100,   73,   74,
      295,   80,   80,   80,  295,  102,  295,  101,  236,   77,

       86,   73,   74,  280,   80,   80,   80,   87,   73,   74,
       77,   80,   80,   80,   88,   89,   73,   74,  295,   80,
       80,   80,  189,  189,  189,  102,   94,   77,  268,   95,
      295,   96,  103,  295,   97,  295,  104,  195,  195,  195,
       77,  295,  121,  241,  241,  241,   98,   77,  295,  295,
      295,  295,  295,  295,  295,   77,   94,  268,  295,   95,
      295,   96,  103,  295,   97,  104,  295,   73,   74,  295,
       80,   80,   80,  295,  295,   98,   73,   74,  114,   80,
       80,   80,  295,  295,  295,  295,  295,  105,   73,   74,
      295,   80,   80,   80,  111,   81,  106,  295,  109,  295,

      107,   81,  112,  295,  295,  295,   77,  108,  114,  188,
      113,  295,  189,  189,  189,   77,  295,  105,   73,   74,
      110,   80,   80,   80,  111,   81,  106,   77,  109,  295,
      107,   81,  112,  295,  295,  295,  108,   73,   74,  113,
       80,   80,   80,   73,   74,  115,   80,   80,   80,  110,
      295,   56,  295,  116,   57,   57,   57,   77,  119,   70,
      117,  295,   71,   71,   71,  118,  295,  120,   73,   74,
      295,   75,   75,   75,  115,  295,   77,  295,  295,  295,
      295,  295,   77,  116,  295,  295,  295,  295,  119,  295,
      117,  295,  295,  295,  118,  295,  295,  120,  128,  129,

      130,  131,  131,  131,  295,  295,  295,   77,  128,  129,
      130,  134,  134,  134,   73,   74,  295,   75,   75,   75,
       73,   74,  295,   80,   80,   80,   73,   74,  295,   80,
       80,   80,  295,  295,  295,   73,   74,  133,   80,   80,
       80,   73,   74,  295,   80,   80,   80,  133,  295,  295,
      295,   73,   74,   77,   80,   80,   80,   73,   74,   77,
       80,   80,   80,  139,   81,   77,  295,  295,  295,  140,
       81,   81,  295,  295,   77,  295,  141,   81,  295,   81,
       77,  295,   81,  295,  295,  295,   81,  142,  295,  295,
       77,   81,  139,  295,   81,  295,   77,  295,  140,  295,

       81,   81,  295,   81,  295,  141,  295,   81,  295,   81,
      148,   81,  295,  295,  295,   81,   81,  142,   73,   74,
       81,   80,   80,   80,   73,   74,  295,   80,   80,   80,
      145,  295,  295,   81,  295,  295,  146,   81,  147,   81,
      148,  295,   81,  295,   81,  295,   81,   81,  295,   81,
      295,   81,  295,  144,   81,  295,   81,  143,  295,  149,
      145,  150,  295,   77,  295,  295,  146,   81,  147,   81,
      191,   81,  295,  192,  192,  192,   81,   81,  295,   81,
       81,  295,  144,  295,   81,   81,   81,  151,  149,  152,
      150,   81,   81,   81,  295,  295,  295,   81,   81,   81,

       81,  154,  295,   81,  295,  153,   81,  295,  295,  194,
      295,   81,  295,   81,  295,   81,  295,  151,  295,  152,
       81,   81,   81,   81,  295,   81,   81,  295,   81,   81,
       81,  154,   81,  295,  153,  295,   81,   81,  295,  295,
       81,  295,  155,   81,  156,  295,   81,  295,  157,   81,
       81,  158,   81,   81,   81,  295,  295,  295,   81,   81,
      295,  159,  295,  295,   81,  295,  295,   81,   81,  295,
      295,  295,  155,  295,  156,   81,   81,  157,   81,  295,
       81,  158,   81,   81,  295,  295,  295,   81,   81,   81,
       81,  159,  295,   81,  295,   81,  160,   81,   81,  295,

       81,  295,   81,  295,  161,   81,  295,  162,  295,   81,
       81,  295,  295,  295,   81,  295,  295,   81,   81,   81,
       81,  295,   81,   81,  295,   81,  160,   81,  295,   81,
       81,   81,  295,  161,  163,   81,  295,  162,  295,  164,
       81,  165,  166,   81,   81,  295,  295,   81,   81,   81,
       81,   81,  295,   81,   81,   81,  167,  168,   81,  295,
       81,  295,  295,  163,   81,   81,  295,  295,  295,  164,
       81,  165,  166,   81,  295,   81,  295,  295,  295,   81,
       81,  295,   81,   81,   81,  167,  168,   81,   81,  169,
      174,  170,   81,  175,   81,   81,  295,  295,  295,   81,

      295,   81,   81,  295,  295,   81,   81,  176,  171,  172,
      295,  173,   81,  295,   81,  295,   81,  295,  169,  295,
      174,  170,   81,  175,   81,  295,  295,  295,  295,  295,
       81,   81,   81,   81,  295,   81,  176,   81,  171,  172,
       81,  173,   81,   81,  295,   81,  177,  178,  295,   81,
       81,  295,  295,  295,  295,  295,   81,   81,  179,  295,
       81,   81,   81,   81,  295,  295,   81,   81,  295,   81,
       81,   81,  180,   81,   81,  177,   81,  178,   81,   81,
       81,   81,   81,  295,  295,  295,   81,   81,  179,   81,
       81,   81,  295,  181,   81,  295,   81,   81,  295,   81,

      295,  295,  180,   81,   81,  295,   81,   81,  182,   81,
       81,  295,   81,  128,  129,  130,  131,  131,  131,   81,
      295,  191,  181,   81,  195,  195,  195,   81,  128,  129,
      130,  134,  134,  134,   81,  295,  295,  182,   81,  128,
      129,  130,  134,  134,  134,  128,  129,  130,  134,  134,
      134,  295,  133,  128,  129,  130,  134,  134,  134,  295,
      194,   73,   74,  295,   80,   80,   80,  133,   73,   74,
      295,   80,   80,   80,   81,  295,  295,  295,  133,  198,
      295,   81,  295,   81,  133,  295,   81,  197,  295,  295,
       81,  295,  133,  295,  295,   81,   81,  295,  295,  295,

       77,  295,  295,   81,   81,  295,  295,   77,   81,  198,
      295,   81,  295,   81,  295,   81,  197,  295,   73,   74,
       81,   80,   80,   80,   81,  295,   81,  295,   81,  199,
      295,  295,  295,   81,   81,   81,  200,   81,  295,  201,
       81,   81,  202,   81,   81,  295,   81,  295,  295,  237,
       81,   81,  238,  238,  238,  210,   81,   77,   81,  199,
      203,  295,  295,  295,   81,   81,  200,  295,  201,   81,
       81,   81,  202,   81,   81,   81,  295,   81,  295,   81,
       81,   81,   81,  204,  210,   81,   81,  295,  240,  203,
      295,   81,  205,  295,   81,  295,  295,  295,  206,  295,

       81,   81,  295,  295,  295,  295,   81,   81,  295,   81,
       81,   81,  204,  295,  208,  295,   81,   81,   81,  295,
       81,  205,   81,  207,   81,   81,   81,  295,  206,  295,
       81,   81,  211,   81,   81,   81,  295,  295,   81,  209,
       81,   81,  295,  295,  208,  295,   81,   81,   81,  295,
      212,   81,  207,   81,   81,   81,   81,  295,  295,   81,
       81,   81,  211,   81,   81,   81,  213,   81,  209,   81,
       81,   81,  295,  295,  214,   81,   81,   81,  295,  295,
      212,   81,   81,   81,   81,  295,  215,  295,  295,   81,
       81,   81,  295,  295,   81,  213,   81,  295,  295,   81,

       81,   81,   81,  295,  214,  295,   81,   81,  295,   81,
       81,   81,  295,  216,   81,   81,  215,  217,  295,   81,
      295,   81,   81,  218,  295,  295,   81,   81,   81,   81,
       81,  219,   81,   81,  295,  295,   81,  295,  295,   81,
      295,   81,  216,   81,  295,   81,  295,  217,   81,  295,
      220,   81,   81,  218,  295,   81,   81,   81,   81,   81,
      221,  219,   81,  295,   81,   81,   81,  295,  222,   81,
       81,  295,   81,  295,   81,  295,  295,  223,   81,  295,
      220,  224,  295,  295,   81,   81,   81,   81,  295,  221,
      295,   81,  295,   81,   81,   81,  225,  222,   81,  295,

       81,   81,   81,  295,   81,   81,  223,  295,   81,  295,
       81,  224,  295,   81,   81,   81,  295,   81,  295,  295,
       81,   81,   81,   81,  295,  225,  295,   81,  295,  295,
       81,   81,   81,  295,   81,  295,   81,   81,   81,  226,
       81,  295,   81,   81,   81,  295,  295,   81,  228,   81,
       81,   81,   81,  295,  295,  295,  295,   81,  295,   81,
      295,   81,  295,  227,   81,  295,   81,   81,   81,  226,
      229,  295,  295,   81,   81,   81,   81,  228,   81,  295,
       81,  295,   81,   81,  295,  295,  295,  295,   81,   81,
       81,  295,  227,   81,  230,  295,   81,   81,   81,  295,

      229,  295,   81,   81,   81,   81,   81,  295,   81,   81,
      295,   81,  231,   81,  295,  295,   81,   81,   81,  295,
       81,  295,  295,  295,  230,   81,   81,   81,  295,  295,
      232,   81,  295,   81,   81,  237,  295,   81,  241,  241,
      241,   81,  231,  295,  295,   81,  191,  295,   81,  192,
      192,  192,  295,  191,  295,   81,  195,  195,  195,  232,
      191,  295,  295,  195,  195,  195,  191,  295,  295,  195,
      195,  195,  191,  295,  240,  195,  195,  195,  243,   81,
      295,  295,  295,  295,  295,  194,   81,  295,  295,   81,
      295,   81,  194,  244,  295,  295,   81,  295,  295,  194,

      295,   81,  295,   81,  295,  194,  295,  295,  243,   81,
       81,  194,  247,  295,  295,   81,   81,  295,  295,   81,
       81,  295,  295,  244,   73,   74,   81,   80,   80,   80,
       81,   73,   74,   81,   80,   80,   80,  295,  248,   81,
       81,   81,  247,  295,   81,  245,  249,  295,   81,   81,
      295,   81,  295,   81,  246,   81,   81,  295,  295,  295,
      295,   81,   81,   77,  295,   81,  295,   81,  248,   81,
       77,   81,   81,  295,  295,  245,  249,   81,   81,   81,
       81,   81,   81,  295,  246,   81,   81,   81,   81,  295,
       81,  295,   81,   81,   81,   81,   81,   81,  295,   81,

      295,  295,   81,   81,   81,  295,   81,  250,  295,   81,
       81,   81,  295,   81,  295,   81,  295,   81,   81,   81,
       81,  295,   81,  295,   81,   81,   81,   81,   81,   81,
      295,   81,  295,   81,   81,  295,   81,  250,   81,   81,
       81,   81,  251,   81,   81,   81,   81,  295,  295,   81,
       81,   81,  253,  252,   81,   81,   81,   81,  295,   81,
       81,   81,   81,  295,  295,  295,   81,   81,  254,   81,
       81,  251,  295,   81,  295,   81,   81,  295,  295,  295,
       81,   81,  253,  252,  295,   81,   81,  295,   81,  295,
      295,   81,   81,   81,  295,  255,   81,   81,  254,  295,

      295,  295,   81,  295,   81,   81,  295,  295,  256,  257,
      258,   81,   81,   81,   81,  295,  295,   81,   81,  295,
       81,   81,   81,  259,  255,   81,   81,   81,  295,  295,
      295,  295,  295,  295,   81,   81,  295,  256,  257,  295,
      258,  295,   81,   81,   81,   81,   81,  295,  295,  295,
       81,   81,   81,  259,   81,   81,  260,   81,   81,  262,
       81,   81,  295,  295,  295,   81,  295,   81,   81,  295,
       81,  261,  263,   81,  295,   81,  295,  295,  295,  295,
       81,  295,   81,  295,  295,  260,   81,   81,   81,  262,
       81,   81,   81,  295,  295,   81,   81,   81,   81,   81,

      261,  263,   81,   81,   81,  264,   81,  295,   81,  295,
       81,   81,  295,   81,  295,  265,   81,   81,   81,  237,
      295,   81,  238,  238,  238,  237,   81,  295,  241,  241,
      241,  295,  295,   81,   81,  264,   81,   81,  295,   81,
      295,   81,   81,   81,  265,   81,   81,   81,  295,   81,
      295,   81,  295,  266,   81,  267,  237,  295,  240,  241,
      241,  241,  237,  295,  240,  241,  241,  241,  295,   81,
      237,  295,   81,  241,  241,  241,   81,  295,  295,   81,
       81,  295,  266,   81,  267,   81,   81,  269,  295,  295,
      295,  295,   81,   81,  295,  240,  295,   81,   81,   73,

       74,  240,   80,   80,   80,  295,   81,   73,   74,  240,
       80,   80,   80,   81,  295,   81,   81,  269,   81,  295,
      295,  295,   81,   81,  295,  295,   81,   81,   81,   73,
       74,  270,   80,   80,   80,   81,   81,   81,   77,  295,
       81,  295,  295,   81,   81,   81,   77,   81,  295,   81,
      295,  295,   81,  271,  295,  295,  295,   81,   81,  295,
      295,  270,  295,  272,   81,   81,  295,   81,   77,   81,
      295,   81,   81,  295,   81,   81,   81,  295,   81,   81,
      295,  295,   81,  271,   81,  273,   81,  295,   81,  295,
      295,   81,  295,  272,   81,   81,  295,  295,   81,  295,

       81,   81,   81,   81,   81,   81,  295,   81,  295,   81,
      295,   81,  295,   81,   81,  273,   81,  274,   81,   81,
      295,   81,  276,   81,   81,   81,   81,  275,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,  295,
      295,   81,  295,   81,   81,   81,  274,  295,   81,  295,
       81,  295,  276,   81,   81,   81,   81,  275,  295,   81,
       81,   81,   81,   81,   81,   81,   81,   81,  295,   81,
      295,   81,  295,   81,   81,   81,   81,  295,   81,  277,
       81,  295,   81,   81,   81,   81,  295,   81,   81,   81,
       81,  295,   81,  295,  295,   81,   81,  295,  295,   81,

       81,  295,  278,   81,  295,   81,   81,   81,   81,  277,
      279,   81,   81,   81,   81,   81,   81,   81,   81,   81,
      295,   81,  295,   81,  295,   81,   81,  281,  295,  295,
       73,   74,  278,   80,   80,   80,   81,  295,  295,  295,
      279,   81,  282,  295,   81,  295,  295,   81,   81,  284,
      295,   81,   81,  295,   81,   81,  281,   73,   74,   81,
       80,   80,   80,  295,  295,  295,  295,  295,   81,   77,
      283,   81,  282,  285,   81,   81,  295,   81,   81,  284,
       81,   81,  295,   81,   81,  295,   81,   81,   81,  295,
       81,  295,  295,  295,   81,  295,   77,   81,   81,   81,

      283,   81,   81,  285,   81,   81,   81,  295,   81,   81,
      295,   81,   81,   81,   81,   81,  287,   81,   81,  286,
       81,   81,   81,  295,   81,  295,   81,   81,   81,   81,
      295,   81,  295,  295,   81,  295,   81,   73,   74,  295,
       80,   80,   80,   81,   81,  295,  287,   81,  286,  295,
      295,   81,   81,  295,  295,   81,  295,  288,  295,   81,
       81,   73,   74,   81,   80,   80,   80,   81,  295,  295,
      295,  295,   81,  290,   81,  289,   77,   81,  295,  291,
      295,   81,  295,  295,   81,  295,   81,  288,  295,   81,
       81,   73,   74,  295,   80,   80,   80,   81,  295,  295,

       77,   81,  290,  295,   81,  289,  295,   81,  295,  291,
       81,   81,   81,   81,   81,   81,  295,   81,   81,   81,
      293,  295,   81,  292,   81,   81,   81,  294,  295,   81,
       77,  295,  295,   81,   81,  295,   81,  295,   81,   81,
       81,   81,   81,   81,  295,  295,  295,   81,  295,   81,
      293,   81,  292,   81,   81,  295,   81,  294,  295,   81,
      295,  295,  295,   81,   81,  295,   81,   81,   81,  295,
       81,   52,   52,   52,   52,   52,   52,   54,   54,   54,
       54,   54,   54,   58,  295,  295,   58,   76,   76,  295,
      295,   76,   81,   81,  295,  295,   81,  132,  132,  132,

      295,  132,  135,  135,  135,  295,  135,  193,  295,  295,
      295,  193,  196,  295,  295,  295,  196,  239,  295,  295,
      295,  239,  242,  295,  295,  295,  242,    5,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,

      295,  295,  295,  295,  295,  295,  295,  295
    } ;

static const flex_int16_t yy_chk[2609] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        9,   12,  305,    9,   12,   12,   12,   20,  304,  299,
       20,   20,   20,   21,   21,    5,   21,   21,   21,   54,

       28,   28,   54,   28,   28,   28,    4,   22,   22,    3,
       22,   22,   22,   56,   56,   56,    0,   12,   18,   18,
       18,   62,   22,   63,   18,   18,   57,   64,   18,   65,
       18,    0,   21,   66,    0,   57,   57,   57,   18,   28,
       18,    0,   68,   18,   18,   18,   22,   70,   70,   70,
        0,   62,   22,   63,    0,   18,   64,    0,   18,   65,
       18,   23,   23,   66,   23,   23,   23,    0,   18,    0,
       18,   68,   18,   18,   18,  122,   23,    0,    0,   31,
       31,    0,   31,   31,   31,   73,   73,   73,  126,  123,
      125,   32,   32,   31,   32,   32,   32,   31,   34,   34,

       23,   34,   34,   34,   32,  122,   23,   29,   29,    0,
       29,   29,   29,  127,  128,  128,  128,  126,   31,  123,
      125,   29,   29,   31,   32,   34,  184,   31,   29,   29,
       32,  136,  136,  136,   32,   74,  185,   34,   74,   74,
       74,    0,    0,  127,   35,   35,   29,   35,   35,   35,
      186,   29,   29,   32,   34,    0,  184,   35,   29,   29,
       30,   30,    0,   30,   30,   30,  185,   35,  187,    0,
       30,   36,   36,  268,   36,   36,   36,   30,    0,    0,
      186,    0,    0,   35,   30,   30,    0,   35,   37,   37,
        0,   37,   37,   37,    0,   36,    0,   35,  187,   30,

       30,   40,   40,  268,   40,   40,   40,   30,   38,   38,
       36,   38,   38,   38,   30,   30,   33,   33,    0,   33,
       33,   33,  188,  188,  188,   36,   33,   37,  233,   33,
        0,   33,   38,    0,   33,    0,   38,  191,  191,  191,
       40,    0,   58,  237,  237,  237,   33,   38,   58,    0,
        0,   58,   58,   58,    0,   33,   33,  233,    0,   33,
        0,   33,   38,    0,   33,   38,    0,   43,   43,    0,
       43,   43,   43,    0,    0,   33,   39,   39,   43,   39,
       39,   39,    0,    0,   58,    0,    0,   39,   41,   41,
        0,   41,   41,   41,   42,   42,   39,    0,   41,    0,

       39,   42,   42,    0,    0,    0,   43,   39,   43,  129,
       42,    0,  129,  129,  129,   39,    0,   39,   44,   44,
       41,   44,   44,   44,   42,   42,   39,   41,   41,    0,
       39,   42,   42,    0,    0,    0,   39,   45,   45,   42,
       45,   45,   45,   46,   46,   44,   46,   46,   46,   41,
        0,   59,    0,   45,   59,   59,   59,   44,   46,  130,
       45,    0,  130,  130,  130,   45,    0,   46,   60,   60,
        0,   60,   60,   60,   44,    0,   45,    0,    0,    0,
        0,    0,   46,   45,    0,    0,    0,   59,   46,    0,
       45,    0,    0,    0,   45,    0,    0,   46,   71,   71,

       71,   71,   71,   71,    0,    0,    0,   60,   72,   72,
       72,   72,   72,   72,   75,   75,    0,   75,   75,   75,
       76,   76,    0,   76,   76,   76,   77,   77,    0,   77,
       77,   77,    0,    0,    0,   78,   78,   71,   78,   78,
       78,   79,   79,    0,   79,   79,   79,   72,    0,    0,
        0,   80,   80,   75,   80,   80,   80,   81,   81,   76,
       81,   81,   81,   78,   82,   77,    0,    0,    0,   79,
       83,   82,    0,    0,   78,    0,   82,   83,    0,   84,
       79,    0,   83,    0,    0,    0,   84,   84,    0,    0,
       80,   84,   78,    0,   82,    0,   81,    0,   79,    0,

       83,   82,    0,   88,    0,   82,    0,   83,    0,   84,
       88,   83,    0,    0,    0,   88,   84,   84,   85,   85,
       84,   85,   85,   85,   86,   86,    0,   86,   86,   86,
       87,    0,    0,   88,    0,    0,   87,   87,   87,   89,
       88,    0,   87,    0,   88,    0,   89,   90,    0,   91,
        0,   89,    0,   86,   90,    0,   91,   85,    0,   90,
       87,   91,    0,   86,    0,    0,   87,   87,   87,   89,
      137,   87,    0,  137,  137,  137,   89,   90,    0,   91,
       89,    0,   86,    0,   90,   92,   91,   92,   90,   93,
       91,   93,   92,   94,    0,    0,    0,   92,   93,   95,

       94,   95,    0,   93,    0,   94,   95,    0,    0,  137,
        0,   95,    0,   96,    0,   92,    0,   92,    0,   93,
       96,   93,   92,   94,    0,   96,   92,    0,   93,   95,
       94,   95,   93,    0,   94,    0,   95,   97,    0,    0,
       95,    0,   97,   96,   97,    0,   98,    0,   97,   97,
       96,   98,   99,   98,   96,    0,    0,    0,   98,   99,
        0,   99,    0,    0,   99,    0,    0,   97,  100,    0,
        0,    0,   97,    0,   97,  100,   98,   97,   97,    0,
      100,   98,   99,   98,    0,    0,    0,   98,  101,   99,
      102,   99,    0,   99,    0,  101,  101,  102,  100,    0,

      101,    0,  102,    0,  102,  100,    0,  103,    0,  100,
      104,    0,    0,    0,  103,    0,    0,  104,  101,  103,
      102,    0,  104,  105,    0,  101,  101,  102,    0,  101,
      105,  102,    0,  102,  105,  105,    0,  103,    0,  106,
      104,  106,  106,  107,  103,    0,    0,  104,  103,  106,
      107,  104,    0,  105,  106,  107,  106,  107,  108,    0,
      105,    0,    0,  105,  105,  108,    0,    0,    0,  106,
      108,  106,  106,  107,    0,  109,    0,    0,    0,  106,
      107,    0,  109,  106,  107,  106,  107,  109,  108,  109,
      112,  110,  112,  112,  110,  108,    0,    0,    0,  108,

        0,  110,  111,    0,    0,  109,  110,  112,  111,  111,
        0,  111,  109,    0,  111,    0,  109,    0,  109,    0,
      112,  110,  112,  112,  110,    0,    0,    0,    0,    0,
      114,  110,  111,  113,    0,  110,  112,  114,  111,  111,
      113,  111,  114,  111,    0,  113,  113,  115,    0,  115,
      116,    0,    0,    0,    0,    0,  115,  116,  116,    0,
      114,  115,  116,  113,    0,    0,  117,  114,    0,  119,
      113,  114,  117,  117,  113,  113,  119,  115,  117,  115,
      116,  119,  118,    0,    0,    0,  115,  116,  116,  118,
      115,  116,    0,  118,  118,    0,  117,  120,    0,  119,

        0,    0,  117,  117,  120,    0,  119,  117,  120,  120,
      119,    0,  118,  131,  131,  131,  131,  131,  131,  118,
        0,  138,  118,  118,  138,  138,  138,  120,  132,  132,
      132,  132,  132,  132,  120,    0,    0,  120,  120,  133,
      133,  133,  133,  133,  133,  134,  134,  134,  134,  134,
      134,    0,  131,  135,  135,  135,  135,  135,  135,    0,
      138,  139,  139,    0,  139,  139,  139,  132,  140,  140,
        0,  140,  140,  140,  141,    0,    0,    0,  133,  142,
        0,  141,    0,  142,  134,    0,  141,  141,    0,    0,
      142,    0,  135,    0,    0,  142,  144,    0,    0,    0,

      139,    0,    0,  144,  141,    0,    0,  140,  144,  142,
        0,  141,    0,  142,    0,  141,  141,    0,  143,  143,
      142,  143,  143,  143,  142,    0,  144,    0,  145,  143,
        0,    0,    0,  144,  146,  145,  143,  144,    0,  145,
      145,  146,  146,  154,  147,    0,  146,    0,    0,  189,
      154,  147,  189,  189,  189,  154,  147,  143,  145,  143,
      147,    0,    0,    0,  146,  145,  143,    0,  145,  145,
      148,  146,  146,  154,  147,  146,    0,  148,    0,  149,
      154,  147,  148,  148,  154,  147,  149,    0,  189,  147,
        0,  149,  149,    0,  150,    0,    0,    0,  150,    0,

      148,  150,    0,    0,    0,    0,  150,  148,    0,  149,
      151,  148,  148,    0,  152,    0,  149,  151,  152,    0,
      149,  149,  151,  151,  150,  152,  153,    0,  150,    0,
      152,  150,  155,  153,  155,  150,    0,    0,  153,  153,
      151,  155,    0,    0,  152,    0,  155,  151,  152,    0,
      156,  151,  151,  156,  157,  152,  153,    0,    0,  152,
      156,  157,  155,  153,  155,  156,  157,  153,  153,  158,
      159,  155,    0,    0,  158,  155,  158,  159,    0,    0,
      156,  158,  159,  156,  157,    0,  160,    0,    0,  160,
      156,  157,    0,    0,  156,  157,  160,    0,    0,  158,

      159,  160,  161,    0,  158,    0,  158,  159,    0,  161,
      158,  159,    0,  161,  161,  162,  160,  162,    0,  160,
        0,  163,  162,  162,    0,    0,  160,  162,  163,  164,
      160,  164,  161,  163,    0,    0,  164,    0,    0,  161,
        0,  164,  161,  161,    0,  162,    0,  162,  165,    0,
      165,  163,  162,  162,    0,  165,  162,  166,  163,  164,
      165,  164,  163,    0,  166,  167,  164,    0,  166,  166,
      164,    0,  167,    0,  168,    0,    0,  167,  165,    0,
      165,  168,    0,    0,  169,  165,  168,  166,    0,  165,
        0,  169,    0,  170,  166,  167,  169,  166,  166,    0,

      170,  171,  167,    0,  168,  170,  167,    0,  171,    0,
      172,  168,    0,  171,  169,  168,    0,  172,    0,    0,
      173,  169,  172,  170,    0,  169,    0,  173,    0,    0,
      170,  171,  173,    0,  170,    0,  176,  174,  171,  174,
      172,    0,  171,  176,  174,    0,    0,  172,  176,  174,
      173,  172,  175,    0,    0,    0,    0,  173,    0,  175,
        0,  173,    0,  175,  175,    0,  176,  174,  179,  174,
      177,    0,    0,  176,  174,  179,  177,  176,  174,    0,
      179,    0,  175,  177,    0,    0,    0,    0,  177,  175,
      181,    0,  175,  175,  178,    0,  178,  181,  179,    0,

      177,    0,  181,  178,  180,  179,  177,    0,  178,  179,
        0,  180,  180,  177,    0,    0,  180,  177,  182,    0,
      181,    0,    0,    0,  178,  182,  178,  181,    0,    0,
      182,  181,    0,  178,  180,  190,    0,  178,  190,  190,
      190,  180,  180,    0,    0,  180,  192,    0,  182,  192,
      192,  192,    0,  193,    0,  182,  193,  193,  193,  182,
      194,    0,    0,  194,  194,  194,  195,    0,    0,  195,
      195,  195,  196,    0,  190,  196,  196,  196,  197,  197,
        0,    0,    0,    0,    0,  192,  197,    0,    0,  198,
        0,  197,  193,  198,    0,    0,  198,    0,    0,  194,

        0,  198,    0,  201,    0,  195,    0,    0,  197,  197,
      201,  196,  201,    0,    0,  201,  197,    0,    0,  198,
      197,    0,    0,  198,  199,  199,  198,  199,  199,  199,
      198,  200,  200,  201,  200,  200,  200,    0,  202,  203,
      201,  202,  201,    0,  201,  199,  203,    0,  202,  204,
        0,  203,    0,  202,  200,  205,  204,    0,    0,    0,
        0,  204,  205,  199,    0,  206,    0,  205,  202,  203,
      200,  202,  206,    0,    0,  199,  203,  206,  202,  204,
      203,  207,  202,    0,  200,  205,  204,  208,  207,    0,
      204,    0,  205,  207,  208,  206,  205,  209,    0,  208,

        0,    0,  206,  210,  209,    0,  206,  210,    0,  209,
      210,  207,    0,  211,    0,  210,    0,  208,  207,  212,
      211,    0,  207,    0,  208,  211,  212,  209,  208,  213,
        0,  212,    0,  210,  209,    0,  213,  210,  209,  214,
      210,  213,  213,  211,  210,  216,  214,    0,    0,  212,
      211,  214,  216,  215,  211,  215,  212,  216,    0,  213,
      212,  217,  215,    0,    0,    0,  213,  215,  217,  214,
      213,  213,    0,  217,    0,  216,  214,    0,    0,    0,
      214,  218,  216,  215,    0,  215,  216,    0,  218,    0,
        0,  217,  215,  218,    0,  218,  215,  219,  217,    0,

        0,    0,  217,    0,  219,  220,    0,    0,  219,  219,
      220,  218,  220,  221,  222,    0,    0,  220,  218,    0,
      221,  222,  218,  222,  218,  221,  222,  219,    0,    0,
        0,    0,    0,    0,  219,  220,    0,  219,  219,    0,
      220,    0,  220,  221,  222,  223,  220,    0,    0,    0,
      221,  222,  223,  222,  221,  222,  223,  223,  224,  225,
      226,  225,    0,    0,    0,  224,    0,  226,  225,    0,
      224,  224,  226,  225,    0,  223,    0,    0,    0,    0,
      229,    0,  223,    0,    0,  223,  223,  229,  224,  225,
      226,  225,  229,    0,    0,  224,  227,  226,  225,  224,

      224,  226,  225,  227,  228,  227,  230,    0,  227,    0,
      229,  228,    0,  230,    0,  228,  228,  229,  230,  238,
        0,  229,  238,  238,  238,  239,  227,    0,  239,  239,
      239,    0,    0,  227,  228,  227,  230,  227,    0,  231,
        0,  228,  232,  230,  228,  228,  231,  230,    0,  232,
        0,  231,    0,  231,  232,  232,  240,    0,  238,  240,
      240,  240,  241,    0,  239,  241,  241,  241,    0,  231,
      242,    0,  232,  242,  242,  242,  231,    0,    0,  232,
      231,    0,  231,  232,  232,  243,  244,  243,    0,    0,
        0,    0,  243,  244,    0,  240,    0,  243,  244,  288,

      288,  241,  288,  288,  288,    0,  247,  245,  245,  242,
      245,  245,  245,  247,    0,  243,  244,  243,  247,    0,
        0,    0,  243,  244,    0,    0,  243,  244,  248,  246,
      246,  245,  246,  246,  246,  248,  247,  249,  288,    0,
      248,    0,    0,  247,  249,  250,  245,  247,    0,  249,
        0,    0,  250,  246,    0,    0,    0,  250,  248,    0,
        0,  245,    0,  251,  251,  248,    0,  249,  246,  248,
        0,  251,  252,    0,  249,  250,  251,    0,  249,  252,
        0,    0,  250,  246,  252,  253,  250,    0,  254,    0,
        0,  253,    0,  251,  251,  254,    0,    0,  253,    0,

      254,  251,  252,  253,  255,  251,    0,  256,    0,  252,
        0,  255,    0,  252,  256,  253,  255,  255,  254,  256,
        0,  253,  258,  257,  258,  254,  259,  257,  253,  254,
      257,  258,  253,  259,  255,  257,  258,  256,  259,    0,
        0,  255,    0,  260,  256,  255,  255,    0,  256,    0,
      260,    0,  258,  257,  258,  260,  259,  257,    0,  261,
      257,  258,  262,  259,  257,  258,  261,  259,    0,  262,
        0,  261,    0,  260,  262,  263,  264,    0,  265,  263,
      260,    0,  263,  264,  260,  265,    0,  263,  264,  261,
      265,    0,  262,    0,    0,  266,  261,    0,    0,  262,

      261,    0,  266,  262,    0,  263,  264,  266,  265,  263,
      267,  267,  263,  264,  269,  265,  263,  264,  267,  265,
        0,  269,    0,  267,    0,  266,  269,  269,    0,    0,
      270,  270,  266,  270,  270,  270,  266,    0,    0,    0,
      267,  267,  270,    0,  269,    0,    0,  272,  267,  272,
        0,  269,  267,    0,  272,  269,  269,  271,  271,  272,
      271,  271,  271,    0,    0,    0,    0,    0,  273,  270,
      271,  274,  270,  273,  275,  273,    0,  272,  274,  272,
      273,  275,    0,  274,  272,    0,  275,  276,  272,    0,
      277,    0,    0,    0,  276,    0,  271,  277,  273,  276,

      271,  274,  277,  273,  275,  273,  278,    0,  274,  273,
        0,  275,  274,  278,  279,  275,  279,  276,  278,  278,
      277,  279,  281,    0,  276,    0,  279,  277,  276,  281,
        0,  277,    0,    0,  281,    0,  278,  282,  282,    0,
      282,  282,  282,  278,  279,    0,  279,  278,  278,    0,
        0,  279,  281,    0,    0,  279,    0,  282,    0,  281,
      284,  283,  283,  281,  283,  283,  283,  284,    0,    0,
        0,    0,  284,  284,  286,  283,  282,  285,    0,  285,
        0,  286,    0,    0,  285,    0,  286,  282,    0,  285,
      284,  289,  289,    0,  289,  289,  289,  284,    0,    0,

      283,  284,  284,    0,  286,  283,    0,  285,    0,  285,
      287,  286,  290,  291,  285,  286,    0,  287,  285,  290,
      291,    0,  287,  287,  290,  291,  292,  293,    0,  294,
      289,    0,    0,  292,  293,    0,  294,    0,  292,  293,
      287,  294,  290,  291,    0,    0,    0,  287,    0,  290,
      291,  287,  287,  290,  291,    0,  292,  293,    0,  294,
        0,    0,    0,  292,  293,    0,  294,  292,  293,    0,
      294,  296,  296,  296,  296,  296,  296,  297,  297,  297,
      297,  297,  297,  298,    0,    0,  298,  300,  300,    0,
        0,  300,  301,  301,    0,    0,  301,  302,  302,  302,

        0,  302,  303,  303,  303,    0,  303,  306,    0,    0,
        0,  306,  307,    0,    0,    0,  307,  308,    0,    0,
        0,  308,  309,    0,    0,    0,  309,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,

      295,  295,  295,  295,  295,  295,  295,  295
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[105] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ALexico.l"
#line 7 "ALexico.l"
    #include "./Analyzer/parser.h"
    #include <iostream>

    using namespace std;

    int yyfila = 1;
    int yycolum = 0;
#line 1159 "scanner.cpp"

#line 1161 "scanner.cpp"

#define INITIAL 0
#define ComentarioSimple 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 32 "ALexico.l"

#line 1379 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 296 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2528 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 33 "ALexico.l"
{  BEGIN ComentarioSimple; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 34 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Size;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkdisk;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 36 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_F;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 37 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_U;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 38 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Path;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 39 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Rmdisk;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 40 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Bf;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 41 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ff;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Wf;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_BestFit;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_FirstFit;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_WorstFit;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 48 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_K;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_M;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_B;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Fdisk;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Type;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Type2;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 54 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Delete;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Name;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Add;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mount;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 58 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Unmount;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 59 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Id;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 60 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkfs;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 61 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Fs;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 62 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Fast;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 63 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Full;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 64 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_2fs;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 65 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_3fs;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 66 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Login;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Logout;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkgrp;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 69 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Rmgrp;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkusr;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Usr;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Pwd;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 73 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Grp;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 74 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Rmusr;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 75 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Chmod;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 76 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ugo;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 77 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_R;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 78 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkfile;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Cont;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Cat;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 81 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_File;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 82 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Rem;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 83 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Edit;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 84 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ren;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 85 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkdir;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 86 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_P;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 87 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Cp;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 88 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Dest;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 89 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mv;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 90 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Find;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 91 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Chown;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 92 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Chgrp;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 93 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Pause;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 94 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_E;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 95 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_L;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 96 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Rep;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 97 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ruta;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 98 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mbr;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 99 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Disk;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 100 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Inode;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 101 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Journaling;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 102 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Block;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 103 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Bm_Inode;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 104 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Bm_Block;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 105 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Tree;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 106 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Sb;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 107 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ls;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 108 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Exec;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 110 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Punto;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 111 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Menor;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 112 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mayor;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 113 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_CorA;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 114 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_CorC;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 115 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_PuntoC;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 116 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Pot;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 117 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Coma;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 118 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_ParA;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 119 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_ParC;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 120 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_LLaveA;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 121 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_LLaveC;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 122 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Suma;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 123 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Menos;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 124 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Por;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 125 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Igual;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 126 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Dolar;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 127 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_DosPuntos;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 129 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Entero;}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 130 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Cadena;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 131 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Identificador;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 132 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Caracter;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 133 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ruta;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 134 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_RutaC;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 135 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Name2;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 136 "ALexico.l"
{ /* Nada */}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 138 "ALexico.l"
{  cout<<"Error lexico, no se esperaba token:   "<<yytext<<endl;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 139 "ALexico.l"
{  /* No hace nada */ }
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 140 "ALexico.l"
{  yyfila++; yycolum = 0; BEGIN INITIAL; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 141 "ALexico.l"
ECHO;
	YY_BREAK
#line 1968 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ComentarioSimple):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 296 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 296 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 295);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 141 "ALexico.l"

