#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 104
#define YY_END_OF_BUFFER 105
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[297] =
    {   0,
        0,    0,    0,    0,  105,  101,  100,  104,  101,    1,
       91,  101,   83,   84,   89,   87,   82,   88,   75,  101,
       93,   93,   93,   92,   80,   76,   77,   95,   16,   95,
       95,   60,   95,   95,   95,   95,   14,   61,   15,   95,
       52,   43,   95,   95,   95,   95,   78,   79,   81,   85,
       86,  102,  103,    0,   94,    0,    0,    0,    0,   93,
       90,    0,    0,    4,    0,    0,    0,    2,   18,    5,
        0,   98,   98,    0,    0,   93,   95,   95,   95,   95,
       95,   95,   95,    8,   95,   95,   95,   95,   95,   53,
       95,   95,   95,   95,   95,   95,    9,   95,   95,   95,

       95,   95,   95,   73,   95,   95,   95,   55,   95,   95,
       95,   95,   95,   72,   95,   95,   95,   95,   10,   95,
       96,    0,    0,   27,   25,    0,    0,    0,    0,    0,
        0,   98,   98,   98,   98,   98,    0,   99,   99,   30,
       31,   95,   95,   95,   46,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   39,
       95,   95,   95,   64,   95,   95,   95,   95,   95,   95,
       38,   48,   50,   62,   95,   95,   95,   95,   95,   42,
       95,   37,   95,   22,    0,    0,    0,    0,    0,   97,
       97,    0,   99,   99,   99,   99,   99,   95,   95,   95,

       95,   95,   95,   95,   45,   54,   65,   49,   74,   28,
       95,   47,   56,   95,   29,   95,   95,   95,   95,   95,
       95,   26,   95,   95,   95,   95,   95,   95,   95,   63,
       71,   95,   95,    0,   21,    6,   19,    0,   97,   97,
       97,   97,   97,   95,   68,   95,   95,   58,   41,   57,
       17,   95,   66,   95,   32,   95,   51,   95,   95,   34,
       36,   23,   59,   95,   35,   40,   95,   95,    0,   95,
       95,   95,   95,   95,   33,    3,   44,    7,   95,   95,
       20,   11,   95,   95,   95,   95,   24,   95,   70,   69,
       12,   95,   13,   95,   67,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    8,    1,    1,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   19,
       20,   18,   18,   18,   18,   18,   18,   21,   22,   23,
        1,   24,    1,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   41,
       50,   51,   52,   53,   54,    1,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   64,   65,   66,   67,   68,
       69,   70,   41,   71,   72,   73,   74,   75,   76,   77,
       78,   41,   79,    1,   80,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   41,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   41,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   41,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[81] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    3,    4,    2,    2,    2,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        5,    1,    1,    6,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1
    } ;

static const flex_int16_t yy_base[311] =
    {   0,
        0,    0,  107,  104,   96, 2608, 2608, 2608,   78, 2608,
     2608,   67, 2608, 2608, 2608, 2608, 2608,  101, 2608,   73,
       79,   93,  147, 2608, 2608, 2608, 2608,   86,  193,  246,
      165,  177,  302,  184,  225,  257,  279,  324,  382,  287,
      330,  344,  404,  372,  430,  447, 2608, 2608, 2608, 2608,
     2608, 2608, 2608,   97, 2608,   96,  118,  272,  231,  456,
     2608,   94,   95,   85,  102,  117,  123, 2608,  101, 2608,
      168,  463,  477,  171,  294,  493,  503,  509,  517,  523,
      530,  536,  530,  531,  544,  591,  599,  589,  591,  599,
      608,  635,  648,  654,  651,  667,  686,  700,  713,  719,

      739,  722,  755,  761,  771,  806,  807,  787,  815,  834,
      853,  870,  866,  874,  912,  909,  922,  925,  931,  964,
     2608,  148,  182, 2608, 2608,  190,  166,  197,  196,  351,
      414,  993,  999, 1011, 1022, 1039,  214, 1030, 1048, 1054,
     1062, 1052, 1060, 1111, 1080, 1107, 1108, 1123, 1150, 1158,
     1172, 1198, 1178, 1214, 1217, 1234, 1236, 1253, 1267, 1269,
     1288, 1305, 1319, 1332, 1352, 1365, 1368, 1374, 1387, 1400,
     1413, 1414, 1422, 1435, 1462, 1449, 1468, 1484, 1504, 1506,
     1512, 1526, 1528, 2608,  229,  245,  248,  260,  250, 1086,
     1138,  318, 1144, 1573, 1584, 1590, 1596, 1552, 1587, 1613,

     1627, 1626, 1625, 1639, 1642, 1661, 1670, 1678, 1687, 1697,
     1706, 1714, 1723, 1745, 1742, 1761, 1762, 1778, 1781, 1805,
     1820, 1821, 1829, 1837, 1869, 1885, 1879, 1893, 1907, 1921,
     1924, 1938, 1957,  280, 2608, 2608, 2608,  421, 1621, 1989,
     1996, 2002, 2008, 2002, 2003, 2033, 2039, 2038, 2046, 2048,
     2054, 2074, 2090, 2098, 2100, 2106, 2114, 2138, 2154, 2146,
     2162, 2178, 2181, 2194, 2197, 2200, 2213, 2233,  299, 2239,
     2271, 2298, 2266, 2299, 2272, 2305, 2308, 2332, 2341, 2356,
     2608, 2365, 2416, 2423, 2415, 2417, 2418, 2431, 2304, 2448,
     2453, 2462, 2463, 2477, 2479, 2608, 2551, 2557, 2562,   88,

     2566, 2571, 2576, 2581,   87,   81, 2586, 2591, 2596, 2601
    } ;

static const flex_int16_t yy_def[311] =
    {   0,
      296,    1,  297,  297,  296,  296,  296,  296,  298,  296,
      296,  299,  296,  296,  296,  296,  296,  296,  296,  300,
      301,  301,  301,  296,  296,  296,  296,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,   29,  302,  302,  302,  302,  296,  296,  296,  296,
      296,  296,  296,  298,  296,  296,  296,  299,  299,  301,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  303,  304,  296,  305,  301,  301,  301,  301,  301,
      301,  302,   45,   45,   45,  302,  302,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,  106,   45,   45,   45,   45,   45,   45,   45,   45,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  306,
      300,  303,  303,  303,  303,  304,  296,  307,  308,  301,
      301,   45,   45,  301,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,  296,  296,  296,  296,  296,  296,  309,
      310,  296,  307,  307,  307,  307,  308,   45,   45,  301,

      301,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,  296,  296,  296,  296,  296,  309,  309,
      309,  309,  310,   45,   45,  301,  301,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,  296,   45,
      301,  301,   45,   45,   45,   45,   45,   45,   45,   45,
      296,   45,  301,  301,   45,   45,   45,   45,  301,  301,
       45,   45,   45,   45,   45,    0,  296,  296,  296,  296,

      296,  296,  296,  296,  296,  296,  296,  296,  296,  296
    } ;

static const flex_int16_t yy_nxt[2689] =
    {   0,
        6,    7,    8,    7,    7,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   28,   35,   36,   37,   38,   39,   40,   28,   41,
       28,   42,   43,   44,   45,   28,   46,   28,   28,   47,
        6,   48,   49,    6,   28,   29,   30,   31,   32,   33,
       34,   28,   35,   36,   37,   38,   39,   40,   28,   41,
       42,   43,   44,   45,   28,   46,   28,   28,   50,   51,
       55,   56,  191,   55,   57,   57,   57,   71,  139,   73,
       72,   72,   72,   74,   75,  296,   76,   76,   76,   55,

       74,   75,   55,   81,   81,   81,   53,   74,   75,   53,
       76,   76,   76,   57,   57,   57,  296,   59,   60,   60,
       60,  122,   79,  123,   61,   62,  121,  124,   63,  125,
       64,  296,   78,   65,  296,   57,   57,   57,   66,   78,
       67,  126,  296,   68,   69,   70,   78,  127,  296,  128,
      296,  122,   79,  123,  296,   62,  124,  296,   63,  125,
       64,   74,   75,   65,   76,   76,   76,  296,   66,  296,
       67,  126,   68,   69,   70,  184,   80,  127,  128,   74,
       75,  296,   81,   81,   81,   72,   72,   72,   81,   81,
       81,   74,   75,   91,   81,   81,   81,   92,   74,   75,

       78,   81,   81,   81,   93,  184,   80,   74,   75,  187,
       81,   81,   81,  135,  135,  135,  296,  185,   78,  296,
      296,   83,   84,   91,   94,  100,  186,   92,   85,   86,
       78,  138,  138,  138,   93,  296,  188,   78,  187,   74,
       75,  296,   81,   81,   81,   56,   78,  185,   57,   57,
       57,   83,   84,   94,  100,  296,  186,  234,   85,   86,
       74,   75,  101,   81,   81,   81,  188,  190,  190,  190,
       87,   74,   75,  235,   81,   81,   81,   88,   78,  236,
      121,  296,  296,  296,   89,   90,  296,  234,  237,  296,
      296,  296,  101,   74,   75,  102,   81,   81,   81,   78,

       87,   74,   75,  235,   81,   81,   81,   88,  137,  236,
       78,  138,  138,  138,   89,   90,   74,   75,  237,   81,
       81,   81,  296,  269,  296,  102,   95,  281,  296,   96,
      296,   97,   78,  296,   98,  196,  196,  196,   74,   75,
       78,   81,   81,   81,   74,   75,   99,   81,   81,   81,
      296,  296,  269,  296,  109,   78,   95,  281,  296,   96,
      296,   97,  103,  296,   98,  189,  104,  296,  190,  190,
      190,  296,  111,   82,  296,   99,  110,   78,  296,   82,
      112,  296,  296,   78,  109,  296,   74,   75,  113,   81,
       81,   81,  103,  296,  296,  104,   74,   75,  296,   81,

       81,   81,  111,   82,  296,  110,  296,  105,  296,   82,
      112,  296,  296,  115,  296,  296,  106,  113,   74,   75,
      107,   81,   81,   81,  296,   78,  296,  108,   71,  114,
      296,   72,   72,   72,  296,   78,  296,  105,  242,  242,
      242,  296,  115,  296,   74,   75,  106,   81,   81,   81,
      107,  296,  296,  296,  296,  296,  108,   78,  296,  114,
      116,   74,   75,  296,   81,   81,   81,  117,  296,  296,
       74,   75,  118,   76,   76,   76,  119,  129,  130,  131,
      132,  132,  132,   78,  296,  120,  296,  296,  296,  296,
      116,  129,  130,  131,  135,  135,  135,  117,  296,  296,

       78,  118,  296,  296,  296,  296,  119,   74,   75,   78,
       76,   76,   76,  296,  296,  120,  134,   74,   75,  296,
       81,   81,   81,   74,   75,  296,   81,   81,   81,  296,
      134,   74,   75,  296,   81,   81,   81,   74,   75,  296,
       81,   81,   81,  296,   74,   75,   78,   81,   81,   81,
       74,   75,  296,   81,   81,   81,   78,  296,  296,  140,
       82,   82,   78,  296,  296,  141,  296,   82,   82,  296,
       78,  296,  142,   82,   82,  296,   78,  296,  296,  296,
      296,   82,  143,   78,  296,  296,   82,  296,  140,   78,
       82,   82,  296,  296,  141,  296,  296,   82,   82,  296,

      296,  142,   82,  296,   82,   74,   75,  296,   81,   81,
       81,   82,  143,   74,   75,   82,   81,   81,   81,  146,
      296,   82,  296,  296,  296,  147,   82,  148,  149,   82,
      296,   82,  296,   82,  296,  296,   82,  296,   82,  296,
      296,   82,  145,  296,  144,   82,  296,  296,  296,  146,
      150,   82,   78,  296,  296,  147,   82,  148,  149,   82,
       82,  296,   82,  296,  296,   82,   82,  296,   82,  296,
       82,  145,   82,  296,  296,   82,  296,  151,   82,  150,
      152,   82,  153,  296,   82,   82,  296,  296,   82,  296,
       82,   82,  296,  154,  296,   82,   82,   82,  296,  155,

      296,  296,   82,  296,   82,  296,  151,  296,   82,   82,
      152,   82,  153,  296,   82,   82,   82,  296,   82,   82,
      296,   82,  154,   82,  296,   82,  296,   82,   82,  155,
       82,  296,  296,  296,   82,  156,  296,  157,   82,  296,
      296,  158,   82,   82,  296,  296,   82,  296,  159,   82,
       82,  296,   82,   82,  296,   82,   82,   82,  160,   82,
       82,   82,  296,  296,   82,  156,  162,  157,  296,   82,
      158,   82,  296,   82,  296,  296,   82,  161,  159,   82,
       82,   82,   82,  296,   82,  163,   82,  296,  160,   82,
       82,   82,   82,   82,  296,  162,  296,   82,   82,   82,

      296,   82,  296,   82,  296,  296,   82,  161,   82,  296,
       82,  296,  164,   82,  296,  163,  296,   82,  296,  296,
      296,   82,   82,  296,   82,  296,   82,  296,   82,   82,
      296,   82,   82,  165,  296,  166,  167,   82,   82,  296,
      296,  164,   82,   82,   82,   82,  296,   82,   82,   82,
      168,  169,   82,  296,   82,  296,  296,   82,   82,  170,
      296,  171,  296,  165,   82,  166,  167,   82,  296,  296,
      296,   82,  296,   82,   82,   82,   82,   82,   82,  168,
      169,  296,   82,   82,  296,  296,   82,  296,  170,  172,
      173,  171,  174,  296,   82,   82,   82,  175,  296,   82,

      176,   82,  296,   82,   82,   82,  296,  296,   82,  178,
      296,   82,  296,   82,  177,  296,   82,  296,  296,  172,
      173,  296,  174,  296,   82,  296,   82,  175,  296,   82,
      176,  296,  296,   82,   82,  296,  296,   82,  178,   82,
      179,   82,   82,  177,  296,   82,   82,  180,  296,   82,
      296,   82,   82,  296,   82,   82,  296,  296,  181,   82,
      296,   82,   82,  296,   82,  296,  182,   82,   82,   82,
      179,  296,   82,   82,  296,  296,   82,  180,  296,   82,
       82,  296,   82,   82,  296,   82,  296,  296,  181,   82,
      296,   82,   82,   82,   82,  182,   82,  296,   82,  296,

      296,   82,   82,  296,  296,  183,   82,  129,  130,  131,
      132,  132,  132,  129,  130,  131,  135,  135,  135,  296,
      296,  296,  296,  296,   82,  129,  130,  131,  135,  135,
      135,   82,  296,  296,  183,   82,  129,  130,  131,  135,
      135,  135,  296,  296,  192,  296,  134,  193,  193,  193,
      296,  296,  134,  129,  130,  131,  135,  135,  135,  296,
      296,  296,  192,  296,  134,  196,  196,  196,   74,   75,
      296,   81,   81,   81,  296,  134,   74,   75,  296,   81,
       81,   81,   82,  195,  296,  296,  199,  296,  296,   82,
       82,  296,  134,  296,   82,  198,  296,   82,  296,  296,

      238,  195,   82,  239,  239,  239,  296,   78,  296,  296,
       82,  296,   82,  296,  296,   78,  199,   82,  296,   82,
       82,  296,   82,   82,  198,   74,   75,   82,   81,   81,
       81,   82,  296,  296,  296,  296,  200,   82,   82,  241,
       82,  296,  296,  201,   82,   82,  203,   82,  202,   82,
       82,   82,  238,   82,  296,  242,  242,  242,  192,  296,
       82,  193,  193,  193,   78,   82,  200,   82,   82,  204,
      296,  296,  296,  201,   82,   82,  203,  202,   82,   82,
       82,  296,  296,   82,  296,  296,  296,   82,   82,  296,
       82,  241,   82,  205,   82,   82,  296,  195,  204,  296,

       82,  206,   82,  296,  209,  296,  207,  296,   82,   82,
       82,  296,  296,  296,   82,   82,  296,   82,   82,  296,
       82,   82,  205,  296,  296,   82,  296,  296,   82,   82,
      206,  296,   82,  296,  209,   82,  207,  296,   82,   82,
       82,  208,  296,   82,   82,   82,  296,   82,  296,   82,
      296,   82,  296,  296,   82,  296,   82,  210,   82,  211,
      296,  296,  212,  213,   82,   82,   82,  296,  296,   82,
      208,   82,  296,   82,   82,  296,   82,   82,   82,  296,
      296,   82,  296,   82,   82,   82,  210,  296,  211,  296,
       82,  296,  212,  213,   82,  214,   82,   82,  296,   82,

      296,   82,  215,   82,   82,   82,   82,   82,  296,   82,
      296,   82,  296,   82,  296,  216,  296,  296,   82,  296,
       82,  296,  296,  296,  214,   82,  296,   82,  296,   82,
       82,  296,  215,  296,   82,   82,   82,  296,   82,  296,
       82,  296,   82,  296,  296,  216,  217,   82,   82,   82,
      296,  218,  296,  296,  296,   82,   82,  219,  296,   82,
      296,   82,   82,  296,  296,   82,  296,  296,  296,   82,
      296,  296,   82,  296,   82,  217,   82,  296,  296,   82,
      296,  218,   82,  296,  220,  296,   82,  219,  296,   82,
       82,  296,   82,  296,   82,   82,  296,  221,   82,   82,

      296,  296,   82,   82,   82,   82,  296,  222,  296,  223,
       82,   82,   82,  296,  220,  296,  224,   82,  296,   82,
      296,  296,  296,   82,  225,   82,  296,  221,   82,   82,
       82,  296,   82,  296,   82,   82,  222,   82,  223,   82,
      296,   82,  226,   82,   82,  224,  296,   82,  296,  296,
       82,   82,   82,  296,  225,   82,   82,  296,   82,   82,
       82,  296,  296,  296,   82,   82,  296,   82,  296,  296,
      296,  226,   82,   82,   82,  296,  296,   82,  296,   82,
       82,   82,   82,  296,   82,   82,   82,  296,  296,   82,
      228,   82,   82,   82,  227,   82,  296,  296,   82,   82,

      296,  296,   82,  296,   82,   82,   82,  296,  230,   82,
      229,  296,  296,  296,   82,  296,   82,  296,  296,  228,
       82,   82,   82,  296,  227,  296,   82,  296,   82,   82,
      296,  296,  231,   82,   82,   82,   82,  296,  230,  229,
      296,   82,   82,   82,   82,  296,   82,  296,   82,   82,
      232,   82,  296,  296,   82,   82,   82,  296,   82,  296,
      296,  296,  231,   82,   82,   82,   82,  296,   82,  296,
      233,   82,   82,   82,  296,   82,  296,   82,  296,   82,
      232,  244,   82,   82,  296,  296,   82,  192,   82,   82,
      196,  196,  196,   82,   82,   82,  296,   82,  192,  233,

      296,  196,  196,  196,  192,  296,  296,  196,  196,  196,
      192,  244,   82,  196,  196,  196,  296,   82,  296,   82,
      296,  245,  296,   82,   82,  296,  195,   74,   75,   82,
       81,   81,   81,  296,  296,  238,  296,  195,  239,  239,
      239,   74,   75,  195,   81,   81,   81,   82,  246,  195,
      296,  245,  249,  296,   82,   82,   82,  296,   82,  296,
      296,  296,   82,   82,  247,  248,   78,   82,   82,   82,
      296,  296,   82,  296,  241,  296,  250,  296,  246,   82,
       78,   82,  249,  296,   82,   82,   82,  296,  296,  296,
      296,   82,   82,   82,  247,  248,   82,   82,   82,   82,

       82,  296,   82,   82,  296,  296,  250,   82,   82,   82,
       82,  296,   82,   82,  296,   82,  296,   82,  296,  296,
       82,   82,  296,  296,   82,  296,  296,   82,   82,   82,
       82,  296,   82,  296,   82,  296,   82,   82,   82,   82,
      251,   82,  296,   82,   82,   82,  296,   82,   82,   82,
      296,   82,  296,   82,   82,  296,   82,   82,   82,  296,
       82,  296,  296,  296,   82,   82,   82,  296,   82,  296,
      251,  296,   82,   82,   82,   82,  296,   82,  296,   82,
      296,   82,   82,   82,   82,   82,  296,   82,  252,  253,
       82,   82,   82,  296,   82,  296,  296,  296,   82,  254,

      296,  296,   82,   82,   82,   82,  296,  296,   82,   82,
      296,   82,   82,   82,  296,  255,   82,  252,   82,  253,
       82,   82,   82,   82,  296,  256,  296,  296,   82,  254,
      296,  296,   82,   82,  296,   82,  296,  296,   82,  296,
      296,   82,   82,  296,  296,  255,  257,  258,   82,   82,
       82,   82,   82,  296,  256,  259,  296,   82,   82,   82,
      296,  296,   82,   82,  296,   82,   82,   82,  260,  296,
      296,   82,   82,  296,   82,  257,  258,  296,  261,   82,
       82,   82,  296,  296,  296,  259,  296,   82,   82,   82,
      296,   82,   82,  296,  296,  296,   82,   82,  260,   82,

       82,  296,  296,  296,   82,  296,   82,  261,   82,   82,
      296,   82,  262,  263,  296,   82,   82,  296,  296,  296,
      296,  264,   82,   82,  296,  296,  296,   82,  296,   82,
       82,  296,  265,  296,  296,   82,   82,   82,  296,   82,
       82,  262,  296,  263,   82,   82,   82,  296,  266,   82,
      264,   82,   82,   82,   82,  296,   82,  296,   82,  296,
       82,   82,  265,   82,   82,  296,   82,   82,   82,  296,
      296,  296,  296,  296,   82,   82,  296,  266,   82,  296,
       82,   82,  267,  296,   82,  296,  296,   82,   82,  296,
      296,   82,   82,  296,   82,   82,  296,  296,   82,   82,

      268,  296,  296,  238,  296,   82,  242,  242,  242,   82,
      238,  267,  296,  242,  242,  242,  238,   82,  296,  242,
      242,  242,  238,  296,   82,  242,  242,  242,   82,  268,
      296,  296,   82,   82,  270,  296,  296,  296,  296,   82,
       82,  296,  241,  296,   82,   82,  296,   74,   75,  241,
       81,   81,   81,   74,   75,  241,   81,   81,   81,  296,
      296,  241,   82,   82,  270,  296,  296,  296,   82,   82,
       82,  271,  296,   82,   82,   82,   82,  272,   82,  296,
       82,  296,  296,   82,   82,   82,   78,  296,   82,  296,
       82,   82,   78,  296,  296,  296,   82,  296,   82,  296,

      296,  271,  296,  273,   82,   82,   82,  272,   82,   82,
      296,   82,  296,   82,   82,   82,   82,   82,  296,   82,
       82,   82,  274,  296,  296,   82,  296,   82,   82,  296,
       82,  296,   82,  273,   82,   82,   82,   82,  296,  296,
       82,   82,   82,   82,   82,   82,  296,  296,   82,  275,
       82,   82,  274,  296,  296,  296,   82,   82,   82,  296,
       82,   82,  296,  296,  296,   82,   82,   82,   82,   82,
      296,   82,  276,   82,   82,   82,   82,   82,  275,  296,
       82,   82,  277,   82,   82,   82,  296,  296,   82,  296,
      296,   82,   82,  296,  296,  296,   82,  296,   82,   82,

      296,  296,  276,  296,   82,   82,   82,  296,   82,   82,
      296,   82,  277,   82,   82,   82,  296,   82,   82,  296,
       82,   82,   82,   82,   82,   82,  296,   82,  278,   82,
       82,   82,  296,   82,   82,  296,   82,   82,   82,   82,
      296,   82,   82,   82,  296,   82,  296,  296,   82,   82,
      279,  296,   82,  296,   82,   82,  296,   82,  278,  296,
       82,   82,  280,   82,   82,   82,  296,   82,   82,   82,
       82,   82,  296,   82,  296,   82,   82,  296,  296,  296,
      279,   82,  282,  296,   82,   74,   75,  296,   81,   81,
       81,  296,  280,   82,  296,  296,   82,  283,  285,   82,

       82,  296,   82,   82,   82,  296,   82,  296,   82,   82,
       82,  282,   74,   75,   82,   81,   81,   81,   74,   75,
      296,   81,   81,   81,   78,  284,   82,  283,  285,   82,
      296,  296,   82,   82,  286,   82,   82,   82,   82,   82,
      296,   82,   82,   82,  296,   82,  296,   82,  296,  296,
       82,   78,  296,  296,  296,  284,  296,   78,  296,   82,
      296,  296,   82,  296,  286,   82,   82,  296,   82,   82,
       82,   82,   82,  296,   82,   82,   82,  296,   82,   82,
      296,  296,  296,   82,  287,  296,   82,  296,  288,  296,
      296,  296,   82,   82,  296,   82,  296,  296,   82,   82,

      296,   82,   82,   82,  296,  296,  296,   82,   82,  296,
      296,  296,   82,  287,  296,  296,   82,  296,  288,  296,
      296,  296,  296,   82,  296,   82,  296,   82,  296,  296,
       74,   75,   82,   81,   81,   81,   82,   74,   75,  296,
       81,   81,   81,  296,  296,   82,  296,   82,   82,  292,
      289,  290,   82,  296,   82,   82,  296,   82,  291,   82,
       82,   82,   74,   75,  296,   81,   81,   81,   82,   78,
      296,  296,  296,   82,  293,   82,   78,   82,   82,  292,
      289,  290,   82,   82,   82,   82,   82,  291,   82,   82,
       82,   82,   82,   82,  296,   82,  296,  296,   82,  294,

       82,   78,   82,  293,   82,   82,  296,  295,  296,   82,
      296,  296,  296,   82,   82,  296,   82,  296,  296,   82,
       82,   82,   82,   82,   82,  296,  296,  296,  296,  294,
       82,  296,  296,   82,   82,  296,  296,  295,  296,   82,
      296,  296,  296,  296,   82,  296,   82,  296,   82,  296,
       82,   52,   52,   52,   52,   52,   52,   54,   54,   54,
       54,   54,   54,   58,  296,  296,   58,   77,   77,  296,
      296,   77,   82,   82,  296,  296,   82,  133,  133,  133,
      296,  133,  136,  136,  136,  296,  136,  194,  296,  296,
      296,  194,  197,  296,  296,  296,  197,  240,  296,  296,

      296,  240,  243,  296,  296,  296,  243,    5,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296
    } ;

static const flex_int16_t yy_chk[2689] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        9,   12,  306,    9,   12,   12,   12,   20,  305,  300,
       20,   20,   20,   21,   21,    5,   21,   21,   21,   54,

       28,   28,   54,   28,   28,   28,    4,   22,   22,    3,
       22,   22,   22,   56,   56,   56,    0,   12,   18,   18,
       18,   62,   22,   63,   18,   18,   57,   64,   18,   65,
       18,    0,   21,   18,    0,   57,   57,   57,   18,   28,
       18,   66,    0,   18,   18,   18,   22,   67,    0,   69,
        0,   62,   22,   63,    0,   18,   64,    0,   18,   65,
       18,   23,   23,   18,   23,   23,   23,    0,   18,    0,
       18,   66,   18,   18,   18,  122,   23,   67,   69,   31,
       31,    0,   31,   31,   31,   71,   71,   71,   74,   74,
       74,   32,   32,   31,   32,   32,   32,   31,   34,   34,

       23,   34,   34,   34,   32,  122,   23,   29,   29,  127,
       29,   29,   29,  129,  129,  129,    0,  123,   31,    0,
        0,   29,   29,   31,   32,   34,  126,   31,   29,   29,
       32,  137,  137,  137,   32,    0,  128,   34,  127,   35,
       35,    0,   35,   35,   35,   59,   29,  123,   59,   59,
       59,   29,   29,   32,   34,    0,  126,  185,   29,   29,
       30,   30,   35,   30,   30,   30,  128,  189,  189,  189,
       30,   36,   36,  186,   36,   36,   36,   30,   35,  187,
       58,   59,    0,    0,   30,   30,   58,  185,  188,   58,
       58,   58,   35,   37,   37,   36,   37,   37,   37,   30,

       30,   40,   40,  186,   40,   40,   40,   30,   75,  187,
       36,   75,   75,   75,   30,   30,   33,   33,  188,   33,
       33,   33,   58,  234,    0,   36,   33,  269,    0,   33,
        0,   33,   37,    0,   33,  192,  192,  192,   38,   38,
       40,   38,   38,   38,   41,   41,   33,   41,   41,   41,
        0,    0,  234,    0,   41,   33,   33,  269,    0,   33,
        0,   33,   38,    0,   33,  130,   38,    0,  130,  130,
      130,    0,   42,   42,    0,   33,   41,   38,    0,   42,
       42,    0,    0,   41,   41,    0,   44,   44,   42,   44,
       44,   44,   38,    0,    0,   38,   39,   39,    0,   39,

       39,   39,   42,   42,    0,   41,    0,   39,    0,   42,
       42,    0,    0,   44,    0,    0,   39,   42,   43,   43,
       39,   43,   43,   43,    0,   44,    0,   39,  131,   43,
        0,  131,  131,  131,    0,   39,    0,   39,  238,  238,
      238,    0,   44,    0,   45,   45,   39,   45,   45,   45,
       39,    0,    0,    0,    0,    0,   39,   43,    0,   43,
       45,   46,   46,    0,   46,   46,   46,   45,    0,    0,
       60,   60,   45,   60,   60,   60,   46,   72,   72,   72,
       72,   72,   72,   45,    0,   46,    0,    0,    0,    0,
       45,   73,   73,   73,   73,   73,   73,   45,    0,    0,

       46,   45,    0,    0,    0,    0,   46,   76,   76,   60,
       76,   76,   76,    0,    0,   46,   72,   77,   77,    0,
       77,   77,   77,   78,   78,    0,   78,   78,   78,    0,
       73,   79,   79,    0,   79,   79,   79,   80,   80,    0,
       80,   80,   80,    0,   81,   81,   76,   81,   81,   81,
       82,   82,    0,   82,   82,   82,   77,    0,    0,   79,
       83,   84,   78,    0,    0,   80,    0,   83,   84,    0,
       79,    0,   83,   84,   85,    0,   80,    0,    0,    0,
        0,   85,   85,   81,    0,    0,   85,    0,   79,   82,
       83,   84,    0,    0,   80,    0,    0,   83,   84,    0,

        0,   83,   84,    0,   85,   86,   86,    0,   86,   86,
       86,   85,   85,   87,   87,   85,   87,   87,   87,   88,
        0,   89,    0,    0,    0,   88,   88,   88,   89,   90,
        0,   88,    0,   89,    0,    0,   90,    0,   91,    0,
        0,   90,   87,    0,   86,   91,    0,    0,    0,   88,
       91,   89,   87,    0,    0,   88,   88,   88,   89,   90,
       88,    0,   89,    0,    0,   92,   90,    0,   91,    0,
       90,   87,   92,    0,    0,   91,    0,   92,   93,   91,
       93,   95,   94,    0,   94,   93,    0,    0,   95,    0,
       93,   94,    0,   95,    0,   92,   94,   96,    0,   96,

        0,    0,   92,    0,   96,    0,   92,    0,   93,   96,
       93,   95,   94,    0,   94,   93,   97,    0,   95,   93,
        0,   94,   95,   97,    0,   94,    0,   96,   97,   96,
       98,    0,    0,    0,   96,   98,    0,   98,   96,    0,
        0,   98,   98,   99,    0,    0,   97,    0,   99,  100,
       99,    0,  102,   97,    0,   99,  100,   97,  100,  102,
       98,  100,    0,    0,  102,   98,  102,   98,    0,  101,
       98,   98,    0,   99,    0,    0,  101,  101,   99,  100,
       99,  101,  102,    0,   99,  103,  100,    0,  100,  102,
      100,  104,  103,  102,    0,  102,    0,  103,  104,  101,

        0,  105,    0,  104,    0,    0,  101,  101,  105,    0,
      101,    0,  105,  105,    0,  103,    0,  108,    0,    0,
        0,  104,  103,    0,  108,    0,  103,    0,  104,  108,
        0,  105,  104,  106,    0,  106,  106,  107,  105,    0,
        0,  105,  105,  106,  107,  109,    0,  108,  106,  107,
      106,  107,  109,    0,  108,    0,    0,  109,  108,  109,
        0,  110,    0,  106,  110,  106,  106,  107,    0,    0,
        0,  110,    0,  106,  107,  109,  110,  106,  107,  106,
      107,    0,  109,  111,    0,    0,  109,    0,  109,  111,
      111,  110,  111,    0,  110,  111,  113,  112,    0,  112,

      112,  110,    0,  113,  114,  110,    0,    0,  113,  113,
        0,  114,    0,  111,  112,    0,  114,    0,    0,  111,
      111,    0,  111,    0,  111,    0,  113,  112,    0,  112,
      112,    0,    0,  113,  114,    0,    0,  113,  113,  116,
      115,  114,  115,  112,    0,  114,  116,  116,    0,  115,
        0,  116,  117,    0,  115,  118,    0,    0,  117,  117,
        0,  119,  118,    0,  117,    0,  118,  118,  119,  116,
      115,    0,  115,  119,    0,    0,  116,  116,    0,  115,
      116,    0,  117,  115,    0,  118,    0,    0,  117,  117,
        0,  119,  118,  117,  120,  118,  118,    0,  119,    0,

        0,  120,  119,    0,    0,  120,  120,  132,  132,  132,
      132,  132,  132,  133,  133,  133,  133,  133,  133,    0,
        0,    0,    0,    0,  120,  134,  134,  134,  134,  134,
      134,  120,    0,    0,  120,  120,  135,  135,  135,  135,
      135,  135,    0,    0,  138,    0,  132,  138,  138,  138,
        0,    0,  133,  136,  136,  136,  136,  136,  136,    0,
        0,    0,  139,    0,  134,  139,  139,  139,  140,  140,
        0,  140,  140,  140,    0,  135,  141,  141,    0,  141,
      141,  141,  142,  138,    0,    0,  143,    0,    0,  142,
      143,    0,  136,    0,  142,  142,    0,  143,    0,    0,

      190,  139,  143,  190,  190,  190,    0,  140,    0,    0,
      145,    0,  142,    0,    0,  141,  143,  145,    0,  142,
      143,    0,  145,  142,  142,  144,  144,  143,  144,  144,
      144,  143,    0,    0,    0,    0,  144,  146,  147,  190,
      145,    0,    0,  144,  146,  147,  147,  145,  146,  146,
      147,  145,  191,  148,    0,  191,  191,  191,  193,    0,
      148,  193,  193,  193,  144,  148,  144,  146,  147,  148,
        0,    0,    0,  144,  146,  147,  147,  146,  146,  147,
      149,    0,    0,  148,    0,    0,    0,  149,  150,    0,
      148,  191,  149,  149,  148,  150,    0,  193,  148,    0,

      150,  150,  151,    0,  153,    0,  151,    0,  153,  151,
      149,    0,    0,    0,  151,  153,    0,  149,  150,    0,
      153,  149,  149,    0,    0,  150,    0,    0,  152,  150,
      150,    0,  151,    0,  153,  152,  151,    0,  153,  151,
      152,  152,    0,  151,  154,  153,    0,  155,    0,  153,
        0,  154,    0,    0,  155,    0,  154,  154,  152,  155,
        0,    0,  156,  157,  156,  152,  157,    0,    0,  152,
      152,  156,    0,  157,  154,    0,  156,  155,  157,    0,
        0,  154,    0,  158,  155,  154,  154,    0,  155,    0,
      158,    0,  156,  157,  156,  158,  157,  159,    0,  160,

        0,  156,  159,  157,  159,  156,  160,  157,    0,  159,
        0,  160,    0,  158,    0,  161,    0,    0,  161,    0,
      158,    0,    0,    0,  158,  161,    0,  159,    0,  160,
      161,    0,  159,    0,  159,  162,  160,    0,  159,    0,
      160,    0,  162,    0,    0,  161,  162,  162,  161,  163,
        0,  163,    0,    0,    0,  161,  163,  163,    0,  161,
        0,  163,  164,    0,    0,  162,    0,    0,    0,  164,
        0,    0,  162,    0,  164,  162,  162,    0,    0,  163,
        0,  163,  165,    0,  165,    0,  163,  163,    0,  165,
      163,    0,  164,    0,  165,  166,    0,  166,  167,  164,

        0,    0,  166,  164,  168,  167,    0,  166,    0,  167,
      167,  168,  165,    0,  165,    0,  168,  169,    0,  165,
        0,    0,    0,  165,  169,  166,    0,  166,  167,  169,
      170,    0,  166,    0,  168,  167,  166,  170,  167,  167,
        0,  168,  170,  171,  172,  168,    0,  169,    0,    0,
      171,  172,  173,    0,  169,  171,  172,    0,  169,  173,
      170,    0,    0,    0,  173,  174,    0,  170,    0,    0,
        0,  170,  174,  171,  172,    0,    0,  174,    0,  176,
      171,  172,  173,    0,  171,  172,  176,    0,    0,  173,
      176,  176,  175,  173,  175,  174,    0,    0,  177,  175,

        0,    0,  174,    0,  175,  177,  174,    0,  178,  176,
      177,    0,    0,    0,  178,    0,  176,    0,    0,  176,
      176,  178,  175,    0,  175,    0,  178,    0,  177,  175,
        0,    0,  179,  175,  179,  177,  180,    0,  178,  177,
        0,  179,  181,  180,  178,    0,  179,    0,  180,  181,
      181,  178,    0,    0,  181,  178,  182,    0,  183,    0,
        0,    0,  179,  182,  179,  183,  180,    0,  182,    0,
      183,  179,  181,  180,    0,  179,    0,  180,    0,  181,
      181,  198,  198,  181,    0,    0,  182,  194,  183,  198,
      194,  194,  194,  182,  198,  183,    0,  182,  195,  183,

        0,  195,  195,  195,  196,    0,    0,  196,  196,  196,
      197,  198,  198,  197,  197,  197,    0,  199,    0,  198,
        0,  199,    0,  198,  199,    0,  194,  200,  200,  199,
      200,  200,  200,    0,    0,  239,    0,  195,  239,  239,
      239,  201,  201,  196,  201,  201,  201,  199,  200,  197,
        0,  199,  203,    0,  199,  203,  202,    0,  199,    0,
        0,    0,  203,  202,  201,  202,  200,  203,  202,  204,
        0,    0,  205,    0,  239,    0,  204,    0,  200,  205,
      201,  204,  203,    0,  205,  203,  202,    0,    0,    0,
        0,  206,  203,  202,  201,  202,  203,  202,  206,  204,

      207,    0,  205,  206,    0,    0,  204,  207,  208,  205,
      204,    0,  207,  205,    0,  208,    0,  209,    0,    0,
      208,  206,    0,    0,  209,    0,    0,  210,  206,  209,
      207,    0,  206,    0,  210,    0,  211,  207,  208,  210,
      211,  207,    0,  211,  212,  208,    0,  209,  211,  208,
        0,  212,    0,  213,  209,    0,  212,  210,  209,    0,
      213,    0,    0,    0,  210,  213,  211,    0,  210,    0,
      211,    0,  215,  211,  212,  214,    0,  211,    0,  215,
        0,  212,  214,  213,  215,  212,    0,  214,  214,  216,
      213,  216,  217,    0,  213,    0,    0,    0,  216,  217,

        0,    0,  215,  216,  217,  214,    0,    0,  218,  215,
        0,  219,  214,  215,    0,  218,  214,  214,  219,  216,
      218,  216,  217,  219,    0,  219,    0,    0,  216,  217,
        0,    0,  216,  217,    0,  220,    0,    0,  218,    0,
        0,  219,  220,    0,    0,  218,  220,  220,  219,  218,
      221,  222,  219,    0,  219,  221,    0,  221,  222,  223,
        0,    0,  221,  222,    0,  220,  223,  224,  223,    0,
        0,  223,  220,    0,  224,  220,  220,    0,  224,  224,
      221,  222,    0,    0,    0,  221,    0,  221,  222,  223,
        0,  221,  222,    0,    0,    0,  223,  224,  223,  225,

      223,    0,    0,    0,  224,    0,  225,  224,  224,  227,
        0,  225,  225,  226,    0,  226,  227,    0,    0,    0,
        0,  227,  226,  228,    0,    0,    0,  226,    0,  225,
      228,    0,  228,    0,    0,  228,  225,  229,    0,  227,
      225,  225,    0,  226,  229,  226,  227,    0,  229,  229,
      227,  230,  226,  228,  231,    0,  226,    0,  230,    0,
      228,  231,  228,  230,  228,    0,  231,  229,  232,    0,
        0,    0,    0,    0,  229,  232,    0,  229,  229,    0,
      232,  230,  232,    0,  231,    0,    0,  233,  230,    0,
        0,  231,  230,    0,  233,  231,    0,    0,  232,  233,

      233,    0,    0,  240,    0,  232,  240,  240,  240,  232,
      241,  232,    0,  241,  241,  241,  242,  233,    0,  242,
      242,  242,  243,    0,  233,  243,  243,  243,  233,  233,
        0,    0,  244,  245,  244,    0,    0,    0,    0,  244,
      245,    0,  240,    0,  244,  245,    0,  246,  246,  241,
      246,  246,  246,  247,  247,  242,  247,  247,  247,    0,
        0,  243,  244,  245,  244,    0,    0,    0,  248,  244,
      245,  246,    0,  244,  245,  248,  249,  247,  250,    0,
      248,    0,    0,  249,  251,  250,  246,    0,  249,    0,
      250,  251,  247,    0,    0,    0,  251,    0,  248,    0,

        0,  246,    0,  252,  252,  248,  249,  247,  250,  248,
        0,  252,    0,  249,  251,  250,  252,  249,    0,  250,
      253,  251,  254,    0,    0,  251,    0,  253,  254,    0,
      255,    0,  253,  252,  252,  254,  256,  255,    0,    0,
      254,  252,  255,  256,  257,  252,    0,    0,  256,  256,
      253,  257,  254,    0,    0,    0,  257,  253,  254,    0,
      255,  253,    0,    0,    0,  254,  256,  255,  258,  254,
        0,  255,  258,  256,  257,  258,  260,  256,  256,    0,
      258,  257,  259,  260,  259,  257,    0,    0,  260,    0,
        0,  259,  261,    0,    0,    0,  259,    0,  258,  261,

        0,    0,  258,    0,  261,  258,  260,    0,  262,  258,
        0,  263,  259,  260,  259,  262,    0,  260,  263,    0,
      262,  259,  261,  263,  264,  259,    0,  265,  264,  261,
      266,  264,    0,  261,  265,    0,  264,  266,  262,  265,
        0,  263,  266,  267,    0,  262,    0,    0,  263,  262,
      267,    0,  263,    0,  264,  267,    0,  265,  264,    0,
      266,  264,  268,  268,  265,  264,    0,  266,  265,  270,
      268,  266,    0,  267,    0,  268,  270,    0,    0,    0,
      267,  270,  270,    0,  267,  271,  271,    0,  271,  271,
      271,    0,  268,  268,    0,    0,  273,  271,  273,  270,

      268,    0,  275,  273,  268,    0,  270,    0,  273,  275,
      270,  270,  272,  272,  275,  272,  272,  272,  289,  289,
        0,  289,  289,  289,  271,  272,  273,  271,  273,  274,
        0,    0,  275,  273,  274,  276,  274,  273,  277,  275,
        0,  274,  276,  275,    0,  277,    0,  276,    0,    0,
      277,  272,    0,    0,    0,  272,    0,  289,    0,  274,
        0,    0,  278,    0,  274,  276,  274,    0,  277,  278,
      274,  279,  276,    0,  278,  277,  276,    0,  279,  277,
        0,    0,    0,  279,  279,    0,  280,    0,  280,    0,
        0,    0,  278,  280,    0,  282,    0,    0,  280,  278,

        0,  279,  282,  278,    0,    0,    0,  282,  279,    0,
        0,    0,  279,  279,    0,    0,  280,    0,  280,    0,
        0,    0,    0,  280,    0,  282,    0,  280,    0,    0,
      283,  283,  282,  283,  283,  283,  282,  284,  284,    0,
      284,  284,  284,    0,    0,  285,    0,  286,  287,  286,
      283,  284,  285,    0,  286,  287,    0,  285,  285,  286,
      287,  288,  290,  290,    0,  290,  290,  290,  288,  283,
        0,    0,    0,  288,  288,  285,  284,  286,  287,  286,
      283,  284,  285,  291,  286,  287,  285,  285,  286,  287,
      291,  288,  292,  293,    0,  291,    0,    0,  288,  292,

      293,  290,  288,  288,  292,  293,    0,  294,    0,  295,
        0,    0,    0,  291,  294,    0,  295,    0,    0,  294,
      291,  295,  292,  293,  291,    0,    0,    0,    0,  292,
      293,    0,    0,  292,  293,    0,    0,  294,    0,  295,
        0,    0,    0,    0,  294,    0,  295,    0,  294,    0,
      295,  297,  297,  297,  297,  297,  297,  298,  298,  298,
      298,  298,  298,  299,    0,    0,  299,  301,  301,    0,
        0,  301,  302,  302,    0,    0,  302,  303,  303,  303,
        0,  303,  304,  304,  304,    0,  304,  307,    0,    0,
        0,  307,  308,    0,    0,    0,  308,  309,    0,    0,

        0,  309,  310,    0,    0,    0,  310,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[105] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ALexico.l"
#line 7 "ALexico.l"
    #include "./Analyzer/parser.h"
    #include <iostream>

    using namespace std;

    int yyfila = 1;
    int yycolum = 0;
#line 1175 "scanner.cpp"

#line 1177 "scanner.cpp"

#define INITIAL 0
#define ComentarioSimple 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 32 "ALexico.l"

#line 1395 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 297 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2608 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 33 "ALexico.l"
{  BEGIN ComentarioSimple; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 34 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Size;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkdisk;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 36 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_F;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 37 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_U;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 38 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Path;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 39 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Rmdisk;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 40 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Bf;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 41 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ff;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Wf;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_BestFit;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_FirstFit;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_WorstFit;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 48 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_K;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_M;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_B;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Fdisk;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Type;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Type2;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 54 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Delete;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Name;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Add;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mount;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 58 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Unmount;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 59 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Id;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 60 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkfs;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 61 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Fs;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 62 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Fast;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 63 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Full;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 64 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_2fs;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 65 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_3fs;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 66 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Login;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Logout;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkgrp;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 69 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Rmgrp;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkusr;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Usr;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Pwd;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 73 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Grp;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 74 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Rmusr;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 75 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Chmod;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 76 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ugo;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 77 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_R;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 78 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkfile;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Cont;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Cat;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 81 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_File;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 82 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Rem;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 83 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Edit;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 84 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ren;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 85 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mkdir;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 86 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_P;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 87 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Cp;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 88 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Dest;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 89 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mv;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 90 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Find;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 91 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Chown;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 92 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Chgrp;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 93 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Pause;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 94 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_E;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 95 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_L;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 96 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Rep;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 97 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ruta;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 99 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mbr;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 100 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Disk;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 101 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Inode;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 102 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Journaling;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 103 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Block;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 104 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Bm_Inode;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 105 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Bm_Block;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 106 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Tree;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 107 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Sb;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 108 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ls;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 110 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Exec;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 112 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Punto;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 113 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Menor;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 114 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Mayor;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 115 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_CorA;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 116 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_CorC;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 117 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_PuntoC;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 118 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Pot;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 119 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Coma;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 120 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_ParA;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 121 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_ParC;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 122 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_LLaveA;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 123 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_LLaveC;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 124 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Suma;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 125 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Menos;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 126 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Por;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 127 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Igual;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 128 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Dolar;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 129 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_DosPuntos;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 131 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Entero;}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 132 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Cadena;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 133 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Identificador;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 134 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Caracter;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 135 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Ruta;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 136 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_RutaC;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 137 "ALexico.l"
{ yycolum+= yyleng; strcpy(yylval.TEXT, yytext); return TK_Name2;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 138 "ALexico.l"
{ /* Nada */}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 140 "ALexico.l"
{  cout<<"Error lexico, no se esperaba token:   "<<yytext<<endl;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 141 "ALexico.l"
{  /* No hace nada */ }
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 142 "ALexico.l"
{  yyfila++; yycolum = 0; BEGIN INITIAL; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 143 "ALexico.l"
ECHO;
	YY_BREAK
#line 1984 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ComentarioSimple):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 297 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 297 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 296);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 143 "ALexico.l"

